country_codes = {
    'USA': 'US',
    'France': 'FR',
    'Italy': 'IT',
    'Spain': 'ES',
    'Germany': 'DE',
    'Australia': 'AU',
    'Argentina': 'AR',
    'Chile': 'CL',
    'South Africa': 'ZA',
    'New Zealand': 'NZ',
    'Portugal': 'PT',
    'Austria': 'AT',
    'Hungary': 'HU',
    'Greece': 'GR',
    'Mexico': 'MX',
    'Israel': 'IL',
    'Brazil': 'BR',
    'Uruguay': 'UY',
    'Turkey': 'TR',
    'Croatia': 'HR',
    'Slovenia': 'SI',
    'Canada': 'CA',
    'Georgia': 'GE',
    'Lebanon': 'LB',
    'Romania': 'RO',
    'Serbia': 'RS',
    'Bulgaria': 'BG',
    'India': 'IN',
    'Taiwan': 'TW',
    'Japan': 'JP',
    'Vietnam': 'VN',
    'Moldova': 'MD',
    'Cyprus': 'CY',
    'Kazakhstan': 'KZ',
    'Tunisia': 'TN',
    'South Korea': 'KR',
    'Costa Rica': 'CR',
    'Thailand': 'TH',
    'Singapore': 'SG',
    'Belgium': 'BE',
    'Netherlands': 'NL',
    'Switzerland': 'CH',
    'Denmark': 'DK',
    'Norway': 'NO',
    'Finland': 'FI',
    'Iceland': 'IS',
    'Ireland': 'IE',
    'Scotland': 'GB', 
    'United Kingdom': 'GB',
    'England': 'GB',
    'Russia': 'RU',
    'Philippines': 'PH',
    'Egypt': 'EG',
    'Armenia': 'AM',
    'Kazakhstan': 'KZ',
    # Add more countries as needed
}